apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dify

resources:
  - manifests/namespace/namespace.yaml
  - manifests/namespace/rbac.yaml
  - manifests/configmaps/configmaps.yaml
  - manifests/secrets/secrets.yaml
  - manifests/storage/pvc.yaml
  - manifests/databases/databases.yaml
  - manifests/applications/applications.yaml
  - manifests/networking/ingress.yaml
  - manifests/autoscaling/autoscaling.yaml
  - manifests/network-policies/network-policies.yaml
  - manifests/monitoring/monitoring.yaml

commonLabels:
  app.kubernetes.io/part-of: dify
  managed-by: kustomize
